package fixtures

import (
	"io/fs"
	"os"
	"strings"
	"testing"

	"github.com/defenseunicorns/go-oscal/src/pkg/validation"

	"github.com/risk-sentinel/sparc-horizon/internal/keys"
)

// committedDir is the fixtures tree in the repository, relative to this
// package.
const committedDir = "../../fixtures"

func generate(t *testing.T) Tree {
	t.Helper()
	tree, err := New(keys.ProvisionalNamespace()).Generate()
	if err != nil {
		t.Fatalf("Generate: %v", err)
	}
	return tree
}

// P0's exit criterion, executable: two independent regenerations agree byte
// for byte. Two generators are built rather than one reused, so a generator
// that carried state between runs would fail here.
func TestRegenerationIsStable(t *testing.T) {
	first := generate(t)
	second := generate(t)

	if len(first) != len(second) {
		t.Fatalf("two runs produced %d and %d files", len(first), len(second))
	}
	for _, p := range first.Paths() {
		b, ok := second[p]
		if !ok {
			t.Errorf("%s: present in the first run, absent from the second", p)
			continue
		}
		if string(first[p]) != string(b) {
			t.Errorf("%s: the two runs disagree", p)
		}
	}
}

// Regenerating into two directories and diffing them is the check a person
// runs; this is the same check through the filesystem, which also covers Write
// and the directory layout.
func TestWriteRoundTripsThroughTheFilesystem(t *testing.T) {
	tree := generate(t)
	dir := t.TempDir()
	if err := New(keys.ProvisionalNamespace()).Write(dir); err != nil {
		t.Fatalf("Write: %v", err)
	}
	written := os.DirFS(dir)
	for _, p := range tree.Paths() {
		got, err := fs.ReadFile(written, p)
		if err != nil {
			t.Errorf("%s: %v", p, err)
			continue
		}
		if string(got) != string(tree[p]) {
			t.Errorf("%s: written bytes differ from generated bytes", p)
		}
	}
}

// The committed tree and the generator cannot drift apart silently: a change
// to the generator that is not regenerated fails here rather than at the point
// someone trusts a stale fixture.
func TestCommittedFixturesMatch(t *testing.T) {
	tree := generate(t)

	committed := os.DirFS(committedDir)
	var onDisk []string
	err := fs.WalkDir(committed, ".", func(path string, entry fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if entry.IsDir() {
			return nil
		}
		onDisk = append(onDisk, path)
		return nil
	})
	if err != nil {
		t.Fatalf("walking %s: %v — run `go run ./cmd/genfixtures`", committedDir, err)
	}

	for _, p := range tree.Paths() {
		want := tree[p]
		got, err := fs.ReadFile(committed, p)
		if err != nil {
			t.Errorf("%s: %v — run `go run ./cmd/genfixtures`", p, err)
			continue
		}
		if string(got) != string(want) {
			t.Errorf("%s: the committed fixture differs from the generator's output — run `go run ./cmd/genfixtures`", p)
		}
	}
	for _, p := range onDisk {
		if _, ok := tree[p]; !ok {
			t.Errorf("%s: committed but no longer generated — delete it or restore the generator", p)
		}
	}
}

// Schema validity is measured, not assumed. This is not `sparc-validate` —
// which also enforces the namespace props — but it is the half that can run
// here, and a fixture that is not valid OSCAL fails every consumer downstream.
func TestGeneratedDocumentsAreValidOSCAL(t *testing.T) {
	tree := generate(t)

	validated := 0
	for _, p := range tree.Paths() {
		if !strings.HasPrefix(p, "oscal/") {
			continue
		}
		v, err := validation.NewValidator(tree[p])
		if err != nil {
			t.Errorf("%s: building a validator: %v", p, err)
			continue
		}
		if err := v.Validate(); err != nil {
			t.Errorf("%s: %v", p, err)
			continue
		}
		if got := v.GetSchemaVersion(); got != OSCALVersion {
			t.Errorf("%s: validated against OSCAL %s, want %s", p, got, OSCALVersion)
		}
		validated++
	}
	// A loop that validated nothing reports no failures.
	if want := 4 + 3*len(Boundaries); validated != want {
		t.Errorf("validated %d documents, want %d", validated, want)
	}
}

// The shape #36 specifies: four organizations, seven boundaries, twenty
// systems.
func TestFederationShape(t *testing.T) {
	if len(Orgs) != 4 {
		t.Errorf("%d organizations, want 4", len(Orgs))
	}
	if len(Boundaries) != 7 {
		t.Errorf("%d boundaries, want 7", len(Boundaries))
	}
	if systemCount() != 20 {
		t.Errorf("%d systems, want 20", systemCount())
	}
}

func TestEveryBoundaryNamesAKnownOrganization(t *testing.T) {
	seen := map[string]bool{}
	for _, b := range Boundaries {
		if b.Org().Slug == "" {
			t.Errorf("boundary %q names organization %q, which is not in the table", b.Slug, b.OrgSlug)
		}
		if seen[b.Slug] {
			t.Errorf("duplicate boundary slug %q", b.Slug)
		}
		seen[b.Slug] = true
	}
	if providerBoundary().Slug != ProviderBoundarySlug {
		t.Errorf("the provider boundary %q is not in the table", ProviderBoundarySlug)
	}
}
